# Generated by Django 4.2.5 on 2023-09-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='catagory',
            new_name='Category',
        ),
    ]
